import graph.mutations as mutations
from neo4j import GraphDatabase

def create(log, config, data):
    print('Initializing driver...')
    driver = GraphDatabase.driver(config['neo4j_uri'], auth=(config['neo4j_user'], config['neo4j_password']))
    mutations.graph_clear(log, driver)
    mutations.graph_create_platform(log, driver, data)
    mutations.graph_create_groups(log, driver, data)
    mutations.graph_create_users(log, driver, data)
    mutations.graph_create_tags(log, driver, data)
    mutations.graph_create_categories(log, driver, data)
    mutations.graph_create_topics(log, driver, data)
    mutations.graph_create_posts(log, driver, data)
    mutations.graph_create_replies(log, driver, data)
    mutations.graph_create_quotes(log, driver, data)
    mutations.graph_create_interactions(log, driver)
    mutations.graph_create_likes(log, driver, data)
    mutations.graph_create_languages(log, driver, data)
    mutations.graph_create_projects(log, driver, data)
    mutations.graph_create_codes(log, driver, data)
    mutations.graph_create_code_ancestry(log, driver, data)
    mutations.graph_create_code_names(log, driver, data)
    mutations.graph_create_annotations(log, driver, data)
    mutations.graph_create_code_cooccurrences(log, driver)
    mutations.graph_create_code_use(log, driver)
    driver.close()
